# The default images for all our servers
IMAGE_NAME = "bento/ubuntu-20.04"

# The configurations for masters nodes
K8S_NAME = "k8s-lab"
MASTERS_NUM = 2
MASTERS_CPU = 2 
MASTERS_MEM = 2048

# The configurations for Workers nodes
WORKERS_NUM = 2
WORKERS_CPU = 2
WORKERS_MEM = 2048

IP_BASE = "192.168.56."

VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    (1..MASTERS_NUM).each do |i|      
        config.vm.define "k8s-master-#{i}" do |master|
            master.vm.box = IMAGE_NAME
            master.vm.network "private_network", ip: "#{IP_BASE}#{i + 10}"
            master.vm.hostname = "k8s-master-#{i}"
            master.vm.synced_folder "./instructions_and_materials", "/lab_data", :mount_options => ["dmode=775", "fmode=664"]
            master.vm.provider "virtualbox" do |v|
                v.memory = MASTERS_MEM
                v.cpus = MASTERS_CPU
            end
        end
    end

    (1..WORKERS_NUM).each do |j|
        config.vm.define "k8s-worker-#{j}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "#{IP_BASE}#{j + 10 + MASTERS_NUM}"
            node.vm.hostname = "k8s-worker-#{j}"
            node.vm.synced_folder "./instructions_and_materials", "/lab_data", :mount_options => ["dmode=775", "fmode=664"]
            node.vm.provider "virtualbox" do |v|
                v.memory = WORKERS_MEM
                v.cpus = WORKERS_CPU
                #v.customize ["modifyvm", :id, "--cpuexecutioncap", "20"]
            end
        end
    end
end
